name: CiteIndustrie
version: '${version}'
main: fr.niavlys.dev.ci.main.CiteIndustrie
api-version: '1.21'
authors: [ NiavlySDev ]
commands:
  grade:
    description: Grade Command
  economy:
    description: Economy Command
  money:
    description: Money Command
  convertmoney:
    description: Convert Money Command