name: CiteIndustrie
version: '${version}'
main: fr.niavlys.dev.ci.main.CiteIndustrie
api-version: '1.21'
authors: [ NiavlySDev ]
commands:
  shop:
    description: Shop Command
  grade:
    description: Grade Command
  settings:
    description: Settings Command
  economy:
    description: Economy Command
  money:
    description: Money Command
  reloadshopprice:
    description: ReloadShopPrices Command
  convertmoney:
    description: Convert Money Command