name: CiteDeLindustrie
version: 0.1
main: fr.niavlys.dev.ci.main.Main
author: NiavlyS
api-version: 1.21

commands:
  shop:
    description: Shop command to buy and sell items
    usage: /shop
  grade:
    description: Grade management command
    usage: /grade <player> <grade>
  economy:
    description: Economy management command
    usage: /economy <add|remove|set> <player> <amount>
  settings:
    description: Player settings command
    usage: /settings <language|nick> <value>
